const TILE=32,COLS=15,ROWS=15,canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const MAP=[
'TTTTTTTTTTTTTTT','T....GGGG....TT','T.H..GGGG..S.TT','T....GGGG....TT','T.............T','T..FFFFF......T','T..F...F.GGG..T','T..F...F.GGG..T','T..FFFFF.GGG..T','T........GGG..T','T.GGG.........T','T.GGG..WWWWW..T','T.GGG..W...W..T','T......WWWWW..T','TTTTTTTTTTTTTTT'];
const STARS=[
 {id:'lamine',name:'Lamine Yamal',short:'LY',pos:'DEL',rating:90,color:'#5b7ee5',moves:['Regate eléctrico','Rosca mágica']},
 {id:'mbappe',name:'Kylian Mbappé',short:'KM',pos:'DEL',rating:93,color:'#273c8f',moves:['Velocidad sónica','Disparo cruzado']},
 {id:'aitana',name:'Aitana Bonmatí',short:'AB',pos:'MED',rating:92,color:'#d44f72',moves:['Pase imposible','Control total']},
 {id:'haaland',name:'Erling Haaland',short:'EH',pos:'DEL',rating:92,color:'#58a7d8',moves:['Martillazo','Carga nórdica']},
 {id:'bellingham',name:'Jude Bellingham',short:'JB',pos:'MED',rating:91,color:'#6d3a9c',moves:['Llegada sorpresa','Giro imperial']},
 {id:'alexia',name:'Alexia Putellas',short:'AP',pos:'MED',rating:91,color:'#b53a68',moves:['Visión maestra','Gol de oro']},
 {id:'rodri',name:'Rodri Hernández',short:'RH',pos:'MED',rating:90,color:'#bf3a3a',moves:['Muro táctico','Pase largo']},
 {id:'vinicius',name:'Vinícius Júnior',short:'VJ',pos:'DEL',rating:91,color:'#e0b12d',moves:['Danza veloz','Recorte doble']},
 {id:'cubarsi',name:'Pau Cubarsí',short:'PC',pos:'DEF',rating:86,color:'#cf6a34',moves:['Anticipación','Salida limpia']},
 {id:'courtois',name:'Thibaut Courtois',short:'TC',pos:'POR',rating:90,color:'#54a16a',moves:['Parada gigante','Saque preciso']}
];
const DEFAULT={x:4,y:4,balls:5,owned:['lamine'],captain:'lamine',hp:100,level:5,wins:0};let state=load(),battle=null,moving=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return{...DEFAULT,...JSON.parse(localStorage.getItem('futmon-world')||'{}')}}catch{return{...DEFAULT}}}function save(){localStorage.setItem('futmon-world',JSON.stringify(state));updateHud()}
function updateHud(){$('#ball-count').textContent=state.balls}
function tile(x,y){return MAP[y]?.[x]||'T'}function walkable(t){return '.GHS'.includes(t)}
function drawWorld(){for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)drawTile(x,y,tile(x,y));drawNPC(11,2);drawPlayer(state.x,state.y)}
function rect(x,y,c){ctx.fillStyle=c;ctx.fillRect(x*TILE,y*TILE,TILE,TILE)}
function drawTile(x,y,t){const px=x*TILE,py=y*TILE;if(t==='T'){rect(x,y,'#2d713b');ctx.fillStyle='#1d562b';ctx.fillRect(px+4,py+5,8,17);ctx.fillRect(px+18,py+2,10,22);ctx.fillStyle='#3f9b4f';ctx.fillRect(px,py,32,12)}else if(t==='G'){rect(x,y,'#71b84c');ctx.strokeStyle='#397c38';for(let i=3;i<30;i+=8){ctx.beginPath();ctx.moveTo(px+i,py+29);ctx.lineTo(px+i+3,py+19);ctx.stroke()}}else if(t==='F'){rect(x,y,'#c6a46b');ctx.strokeStyle='#8a6a42';ctx.strokeRect(px+2,py+2,28,28);ctx.fillStyle='#e2c58c';ctx.fillRect(px+5,py+5,22,22)}else if(t==='W'){rect(x,y,'#5ca9d8');ctx.strokeStyle='#b9e5f4';ctx.beginPath();ctx.moveTo(px,py+10);ctx.lineTo(px+10,py+7);ctx.lineTo(px+22,py+10);ctx.stroke()}else{rect(x,y,'#91c765');ctx.fillStyle='#79b255';ctx.fillRect(px,py+25,32,7)}if(t==='H'){rect(x,y,'#ece8d2');ctx.fillStyle='#e34c4c';ctx.fillRect(px+11,py+5,10,22);ctx.fillRect(px+5,py+11,22,10)}if(t==='S'){rect(x,y,'#91c765');ctx.fillStyle='#8b5a2b';ctx.fillRect(px+13,py+10,6,21);ctx.fillStyle='#f1d35a';ctx.fillRect(px+4,py+3,24,14)}}
function sprite(c,x,y,back=false,initials=''){const px=x*TILE,py=y*TILE;ctx.fillStyle='#0004';ctx.fillRect(px+7,py+27,18,4);ctx.fillStyle='#f1b98b';ctx.fillRect(px+10,py+4,12,9);ctx.fillStyle=back?'#d64747':c;ctx.fillRect(px+7,py+13,18,13);ctx.fillStyle='#243247';ctx.fillRect(px+8,py+26,6,5);ctx.fillRect(px+18,py+26,6,5);ctx.fillStyle='white';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText(initials,px+16,py+22)}function drawPlayer(x,y){sprite('#e84d4d',x,y,true,'10')}function drawNPC(x,y){sprite('#5b7ee5',x,y,false,'!')}
function move(dx,dy){if(moving||battle)return;const nx=state.x+dx,ny=state.y+dy;if(!walkable(tile(nx,ny)))return bump();state.x=nx;state.y=ny;save();drawWorld();if(tile(nx,ny)==='G'&&Math.random()<.19)startEncounter();if(tile(nx,ny)==='H'){state.hp=100;save();message('El centro médico ha recuperado a tu capitán.')}if(tile(nx,ny)==='S')message('Explora el césped alto para encontrar estrellas.')}
function bump(){canvas.animate([{transform:'translateX(0)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:120})}
function action(){if(Math.abs(state.x-11)+Math.abs(state.y-2)<=1)dialog('Entrenador: El césped esconde grandes estrellas. Debilítalas antes de lanzar un balón contrato.');else message('No hay nada con lo que interactuar aquí.')}
function message(t){const el=$('#world-message');el.textContent=t;el.style.display='block';clearTimeout(message.t);message.t=setTimeout(()=>el.style.display='none',2600)}function dialog(t){$('#dialog-text').textContent=t;$('#dialog').classList.add('show')}
function startEncounter(){const available=STARS.filter(s=>s.id!==state.captain);const rival=available[Math.floor(Math.random()*available.length)];battle={rival,rivalHp:100,turn:false};$('#flash').classList.add('go');setTimeout(()=>{$('#flash').classList.remove('go');showView('battle-view');setupBattle()},450)}
function setupBattle(){const hero=STARS.find(s=>s.id===state.captain)||STARS[0],r=battle.rival;$('#rival-name').textContent=r.name;$('#rival-level').textContent=Math.max(3,Math.round(r.rating/10));$('#hero-name').textContent=hero.name;$('#hero-level').textContent=state.level;drawBattleSprite($('#rival-sprite'),r,false);drawBattleSprite($('#hero-sprite'),hero,true);updateBattle();battleText(`¡${r.name} aparece en el campo de entrenamiento!`)}
function drawBattleSprite(can,p,back){const c=can.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,128,128);c.fillStyle='#0003';c.beginPath();c.ellipse(64,111,42,10,0,0,Math.PI*2);c.fill();c.fillStyle='#f0b98a';c.fillRect(45,18,38,34);c.fillStyle='#2b2632';c.fillRect(43,14,42,13);c.fillStyle=p.color;c.fillRect(34,51,60,48);c.fillStyle='white';c.font='bold 24px monospace';c.textAlign='center';c.fillText(back?'10':p.short,64,84);c.fillStyle='#273246';c.fillRect(39,99,20,19);c.fillRect(69,99,20,19)}
function updateBattle(){const rh=Math.max(0,battle.rivalHp),hh=Math.max(0,state.hp);$('#rival-hp').style.width=rh+'%';$('#hero-hp').style.width=hh+'%';$('#hero-hp-text').textContent=`${hh}/100`;$('#battle-menu').querySelectorAll('button').forEach(b=>b.disabled=battle.turn);$('#contract-btn').textContent=`⚽ Fichar (${state.balls})`}
function battleText(t){$('#battle-text').textContent=t}
function attack(type){if(battle.turn)return;battle.turn=true;const hero=STARS.find(s=>s.id===state.captain),names={dribble:'un regate brillante',shot:'un disparo potentísimo',press:'una presión asfixiante'},base={dribble:18,shot:27,press:14}[type];let hit=base+Math.floor(Math.random()*12);if(type==='shot'&&Math.random()<.22){battleText(`¡El disparo de ${hero.name} se marcha fuera!`);hit=0}else battleText(`${hero.name} usa ${names[type]}. ¡-${hit} de energía!`);battle.rivalHp-=hit;updateBattle();setTimeout(()=>{if(battle.rivalHp<=0){battle.rivalHp=1;battleText(`${battle.rival.name} está agotado. ¡Ahora es más fácil ficharlo!`);battle.turn=false;updateBattle()}else rivalTurn()},1050)}
function rivalTurn(){const r=battle.rival,move=r.moves[Math.floor(Math.random()*r.moves.length)],damage=9+Math.floor(Math.random()*14);state.hp=Math.max(0,state.hp-damage);save();battleText(`${r.name} usa ${move}. ¡Pierdes ${damage} de energía!`);if(state.hp<=0)setTimeout(()=>endBattle(false,true),1200);else{battle.turn=false;updateBattle()}}
function contract(){if(battle.turn||state.balls<1){if(state.balls<1)battleText('No te quedan balones contrato.');return}state.balls--;save();battle.turn=true;updateBattle();battleText('¡Lanzas un balón contrato!');const chance=.18+(100-battle.rivalHp)*.008+(state.owned.includes(battle.rival.id)?.2:0);setTimeout(()=>{if(Math.random()<chance){if(!state.owned.includes(battle.rival.id))state.owned.push(battle.rival.id);state.wins++;state.level=Math.min(99,state.level+(state.wins%3===0?1:0));save();battleText(`¡Fichaje conseguido! ${battle.rival.name} se une a tu equipo.`);setTimeout(()=>endBattle(true),1600)}else{battleText(`¡${battle.rival.name} rechaza el contrato!`);setTimeout(rivalTurn,900)}},1200)}
function endBattle(caught=false,defeat=false){if(defeat){state.x=2;state.y=2;state.hp=100;save();showView('world-view');message('Tu capitán se agotó. Has vuelto al centro médico.')}else{showView('world-view');message(caught?'¡Nuevo futbolista en tu vestuario!':'Has regresado al mapa.')}battle=null;drawWorld()}
function renderTeam(){const list=state.owned.map(id=>STARS.find(s=>s.id===id)).filter(Boolean);$('#team-list').innerHTML=list.map(p=>`<article class="player-row"><div class="portrait" style="background:${p.color}">${p.short}</div><div><h3>${p.name}</h3><p>${p.pos} · GRL ${p.rating}</p>${state.captain===p.id?'<span class="captain">★ CAPITÁN</span>':''}</div><button data-id="${p.id}">${state.captain===p.id?'✓':'Elegir'}</button></article>`).join('');$$('.player-row button').forEach(b=>b.onclick=()=>{state.captain=b.dataset.id;state.hp=100;save();renderTeam()})}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.remove('active'));if(id==='world-view')$('#nav-world').classList.add('active');if(id==='team-view'){$('#nav-team').classList.add('active');renderTeam()}if(id==='help-view')$('#nav-help').classList.add('active')}
$$('[data-dir]').forEach(b=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();move(...d)}});document.addEventListener('keydown',e=>{const d={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]}[e.key];if(d){e.preventDefault();move(...d)}if(e.key===' '){e.preventDefault();action()}});$('#action-btn').onclick=action;$('#dialog-next').onclick=()=>$('#dialog').classList.remove('show');$('#nav-world').onclick=()=>showView('world-view');$('#nav-team').onclick=()=>showView('team-view');$('#nav-help').onclick=()=>showView('help-view');$$('.close-panel').forEach(b=>b.onclick=()=>showView('world-view'));$$('[data-move]').forEach(b=>b.onclick=()=>attack(b.dataset.move));$('#contract-btn').onclick=contract;$('#run-btn').onclick=()=>endBattle();updateHud();drawWorld();dialog('Bienvenido a FutMon World. Eres una joven promesa: explora Villa Cantera y forma un equipo de estrellas.');
