const TILE=32,VIEW=15,WORLD=48,canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const noise=(x,y,s=0)=>{const n=Math.sin(x*127.1+y*311.7+s*91.3)*43758.5453;return n-Math.floor(n)};
const MAP=Array.from({length:WORLD},(_,y)=>Array.from({length:WORLD},(_,x)=>{
 if(x<2||y<2||x>WORLD-3||y>WORLD-3)return'T';
 if(x>35&&y<18)return noise(x,y)<.55?'S':'G';
 if(x<18&&y>33)return noise(x,y)<.52?'A':'G';
 if(x>33&&y>33)return noise(x,y)<.52?'D':'G';
 return noise(x,y)<.17?'G':'.';
}));
for(let y=2;y<WORLD-2;y++){const x=23+Math.round(Math.sin(y/5)*3);MAP[y][x]=MAP[y][x+1]='W'}
[12,28,40].forEach(y=>{const x=23+Math.round(Math.sin(y/5)*3);for(let i=-1;i<3;i++)MAP[y][x+i]='B'});
for(let x=3;x<WORLD-3;x++){MAP[9][x]='R';MAP[27][x]='R'}for(let y=3;y<WORLD-3;y++)MAP[y][9]='R';
for(let y=20;y<29;y++)for(let x=32;x<45;x++)MAP[y][x]='F';
[[6,6,'H'],[13,6,'M'],[11,11,'S'],[37,22,'S'],[39,39,'S'],[12,39,'S']].forEach(([x,y,t])=>MAP[y][x]=t);
const STARS=[
 {id:'lamine',name:'Lamine Yamal',short:'LY',pos:'DEL',rating:90,color:'#5b7ee5',moves:['Regate eléctrico','Rosca mágica']},
 {id:'mbappe',name:'Kylian Mbappé',short:'KM',pos:'DEL',rating:93,color:'#273c8f',moves:['Velocidad sónica','Disparo cruzado']},
 {id:'aitana',name:'Aitana Bonmatí',short:'AB',pos:'MED',rating:92,color:'#d44f72',moves:['Pase imposible','Control total']},
 {id:'haaland',name:'Erling Haaland',short:'EH',pos:'DEL',rating:92,color:'#58a7d8',moves:['Martillazo','Carga nórdica']},
 {id:'bellingham',name:'Jude Bellingham',short:'JB',pos:'MED',rating:91,color:'#6d3a9c',moves:['Llegada sorpresa','Giro imperial']},
 {id:'alexia',name:'Alexia Putellas',short:'AP',pos:'MED',rating:91,color:'#b53a68',moves:['Visión maestra','Gol de oro']},
 {id:'rodri',name:'Rodri Hernández',short:'RH',pos:'MED',rating:90,color:'#bf3a3a',moves:['Muro táctico','Pase largo']},
 {id:'vinicius',name:'Vinícius Júnior',short:'VJ',pos:'DEL',rating:91,color:'#e0b12d',moves:['Danza veloz','Recorte doble']},
 {id:'cubarsi',name:'Pau Cubarsí',short:'PC',pos:'DEF',rating:86,color:'#cf6a34',moves:['Anticipación','Salida limpia']},
 {id:'courtois',name:'Thibaut Courtois',short:'TC',pos:'POR',rating:90,color:'#54a16a',moves:['Parada gigante','Saque preciso']}
 ,{id:'pedri',name:'Pedri González',short:'PG',pos:'MED',rating:89,color:'#4c8be0',moves:['Pausa maestra','Túnel canario']}
 ,{id:'salma',name:'Salma Paralluelo',short:'SP',pos:'DEL',rating:89,color:'#cf477a',moves:['Sprint total','Remate veloz']}
 ,{id:'musiala',name:'Jamal Musiala',short:'JM',pos:'MED',rating:90,color:'#c33a4c',moves:['Slalom mágico','Toque sutil']}
 ,{id:'saliba',name:'William Saliba',short:'WS',pos:'DEF',rating:88,color:'#355da2',moves:['Cierre perfecto','Choque limpio']}
];
const DEFAULT={x:7,y:7,balls:6,coins:100,owned:['lamine'],captain:'lamine',hp:100,level:5,wins:0,steps:0,chests:[]};let state=load(),battle=null,moving=false,held=null,moveTimer=0,animFrame=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return{...DEFAULT,...JSON.parse(localStorage.getItem('futmon-world')||'{}')}}catch{return{...DEFAULT}}}function save(){localStorage.setItem('futmon-world',JSON.stringify(state));updateHud()}
function updateHud(){$('#ball-count').textContent=state.balls}
function tile(x,y){return MAP[y]?.[x]||'T'}function walkable(t){return!['T','W'].includes(t)}
const zone=()=>state.x>33&&state.y<18?'Ciudad Solar':state.x<18&&state.y>33?'Bosque Cantera':state.x>33&&state.y>33?'Distrito Nocturno':state.x>30&&state.y>18&&state.y<32?'Estadio Central':'Villa Cantera';
function drawWorld(time=animFrame){animFrame=time;const cx=Math.max(0,Math.min(WORLD-VIEW,state.x-7)),cy=Math.max(0,Math.min(WORLD-VIEW,state.y-7));for(let y=0;y<VIEW;y++)for(let x=0;x<VIEW;x++)drawTile(x,y,tile(cx+x,cy+y),cx+x,cy+y,time);drawNPC(11-cx,11-cy);drawPlayer(state.x-cx,state.y-cy);drawChests(cx,cy);}
function rect(x,y,c){ctx.fillStyle=c;ctx.fillRect(x*TILE,y*TILE,TILE,TILE)}
function drawTile(x,y,t,wx=x,wy=y,time=0){const px=x*TILE,py=y*TILE,n=noise(wx,wy);if(t==='T'){rect(x,y,'#245c35');ctx.fillStyle='#19472b';ctx.fillRect(px+3,py+14,26,18);ctx.fillStyle=n>.5?'#3f8e48':'#367c41';ctx.fillRect(px+1,py+2,15,13);ctx.fillRect(px+13,py,18,14)}else if(['G','A','S','D'].includes(t)){const pal=t==='D'?['#57477a','#8168a2']:t==='S'?['#d5b34e','#efd66d']:t==='A'?['#398344','#65ad59']:['#65a94b','#87c361'];rect(x,y,pal[0]);ctx.strokeStyle=pal[1];for(let i=3;i<30;i+=7){const sway=Math.sin(time/300+wx+i)*2;ctx.beginPath();ctx.moveTo(px+i,py+31);ctx.lineTo(px+i+sway,py+18);ctx.stroke()}}else if(t==='F'){rect(x,y,(wx+wy)%2?'#4b994d':'#58aa56');ctx.strokeStyle='#e4f4c388';if(wx===32||wx===44)ctx.strokeRect(px,py,32,32)}else if(t==='W'){rect(x,y,'#3c8fd0');ctx.strokeStyle='#9bdcef';ctx.beginPath();const o=Math.sin(time/350+wy)*3;ctx.moveTo(px,py+10+o);ctx.quadraticCurveTo(px+8,py+5+o,px+16,py+10+o);ctx.quadraticCurveTo(px+24,py+15+o,px+32,py+10+o);ctx.stroke()}else if(t==='B'){rect(x,y,'#3c8fd0');ctx.fillStyle='#9a6c3f';ctx.fillRect(px,py+3,32,26);ctx.strokeStyle='#604429';for(let i=2;i<32;i+=8)ctx.strokeRect(px+i,py+3,1,26)}else if(t==='R'){rect(x,y,'#c7ab75');ctx.fillStyle='#aa8c5d';ctx.fillRect(px+(n*22|0),py+(n*25|0),4,3)}else{rect(x,y,'#91c765')}if(t==='H'){ctx.fillStyle='#f5f0d9';ctx.fillRect(px+3,py+7,26,24);ctx.fillStyle='#d94747';ctx.fillRect(px+12,py+10,8,18);ctx.fillRect(px+7,py+15,18,8)}if(t==='M'){ctx.fillStyle='#f1c95b';ctx.fillRect(px+3,py+7,26,24);ctx.font='16px sans-serif';ctx.fillText('⚽',px+7,py+25)}if(t==='S'){ctx.fillStyle='#7a522d';ctx.fillRect(px+13,py+9,6,22);ctx.fillStyle='#f1d35a';ctx.fillRect(px+4,py+2,24,14)}}
function sprite(c,x,y,back=false,initials=''){if(x<0||x>=VIEW||y<0||y>=VIEW)return;const px=x*TILE,py=y*TILE,bob=held?Math.sin(performance.now()/65)*2:0;ctx.fillStyle='#0004';ctx.fillRect(px+7,py+27,18,4);ctx.fillStyle='#f1b98b';ctx.fillRect(px+10,py+4+bob,12,9);ctx.fillStyle='#2b2632';ctx.fillRect(px+9,py+2+bob,14,5);ctx.fillStyle=back?'#d64747':c;ctx.fillRect(px+7,py+13+bob,18,13);ctx.fillStyle='#243247';ctx.fillRect(px+8,py+26,6,5);ctx.fillRect(px+18,py+26,6,5);ctx.fillStyle='white';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText(initials,px+16,py+22+bob)}function drawPlayer(x,y){sprite('#e84d4d',x,y,true,'10')}function drawNPC(x,y){sprite('#5b7ee5',x,y,false,'!')}
function drawChests(cx,cy){[[18,19],[35,8],[7,42],[40,40],[43,16]].forEach(([x,y],i)=>{if(state.chests.includes(i)||x<cx||x>=cx+VIEW||y<cy||y>=cy+VIEW)return;const px=(x-cx)*32,py=(y-cy)*32;ctx.fillStyle='#6b3f20';ctx.fillRect(px+5,py+11,22,17);ctx.fillStyle='#e4ac38';ctx.fillRect(px+5,py+14,22,5);ctx.fillRect(px+14,py+11,5,17)})}
function move(dx,dy){if(moving||battle||$('#dialog').classList.contains('show'))return;const nx=state.x+dx,ny=state.y+dy;if(!walkable(tile(nx,ny)))return bump();state.x=nx;state.y=ny;state.steps++;$('#zone-name').textContent=zone();if(state.steps%6===0)save();drawWorld();const t=tile(nx,ny);if(['G','A','S','D'].includes(t)&&Math.random()<(t==='G'?.08:.13))startEncounter();if(t==='H'){state.hp=100;save();message('Centro médico: energía recuperada.')}checkChest()}
function bump(){canvas.animate([{transform:'translateX(0)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:120})}
function checkChest(){[[18,19],[35,8],[7,42],[40,40],[43,16]].forEach(([x,y],i)=>{if(state.x===x&&state.y===y&&!state.chests.includes(i)){state.chests.push(i);const reward=2+Math.floor(Math.random()*4);state.balls+=reward;save();dialog(`¡Cofre encontrado! Consigues ${reward} balones contrato.`)}})}
function action(){if(Math.abs(state.x-11)+Math.abs(state.y-11)<=1)dialog('Entrenador: cada región tiene estrellas distintas. Explora Ciudad Solar, el bosque y el Distrito Nocturno.');else if(tile(state.x,state.y)==='M'){if(state.coins>=50){state.coins-=50;state.balls+=3;save();dialog('Has comprado 3 balones contrato por 50 monedas.')}else dialog('Necesitas 50 monedas para comprar 3 balones contrato.')}else message('No hay nada con lo que interactuar aquí.')}
function message(t){const el=$('#world-message');el.textContent=t;el.style.display='block';clearTimeout(message.t);message.t=setTimeout(()=>el.style.display='none',2600)}function dialog(t){$('#dialog-text').textContent=t;$('#dialog').classList.add('show')}
function startEncounter(){const pools={'Ciudad Solar':['vinicius','salma','mbappe','pedri'],'Bosque Cantera':['cubarsi','rodri','aitana','lamine'],'Distrito Nocturno':['bellingham','musiala','haaland','courtois'],'Estadio Central':['mbappe','haaland','aitana','alexia','saliba']},ids=pools[zone()]||STARS.map(s=>s.id),available=STARS.filter(s=>ids.includes(s.id)&&s.id!==state.captain),rival=available[Math.floor(Math.random()*available.length)];battle={rival,rivalHp:100,turn:false,shield:0};$('#flash').classList.add('go');setTimeout(()=>{$('#flash').classList.remove('go');showView('battle-view');setupBattle()},450)}
function setupBattle(){const hero=STARS.find(s=>s.id===state.captain)||STARS[0],r=battle.rival;$('#rival-name').textContent=r.name;$('#rival-level').textContent=Math.max(3,Math.round(r.rating/10));$('#hero-name').textContent=hero.name;$('#hero-level').textContent=state.level;drawBattleSprite($('#rival-sprite'),r,false);drawBattleSprite($('#hero-sprite'),hero,true);updateBattle();battleText(`¡${r.name} aparece en el campo de entrenamiento!`)}
function drawBattleSprite(can,p,back){const c=can.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,128,128);c.fillStyle='#0003';c.beginPath();c.ellipse(64,111,42,10,0,0,Math.PI*2);c.fill();c.fillStyle='#f0b98a';c.fillRect(45,18,38,34);c.fillStyle='#2b2632';c.fillRect(43,14,42,13);c.fillStyle=p.color;c.fillRect(34,51,60,48);c.fillStyle='white';c.font='bold 24px monospace';c.textAlign='center';c.fillText(back?'10':p.short,64,84);c.fillStyle='#273246';c.fillRect(39,99,20,19);c.fillRect(69,99,20,19)}
function updateBattle(){const rh=Math.max(0,battle.rivalHp),hh=Math.max(0,state.hp);$('#rival-hp').style.width=rh+'%';$('#hero-hp').style.width=hh+'%';$('#hero-hp-text').textContent=`${hh}/100`;$('#battle-menu').querySelectorAll('button').forEach(b=>b.disabled=battle.turn);$('#contract-btn').textContent=`⚽ Fichar (${state.balls})`}
function battleText(t){$('#battle-text').textContent=t}
function attack(type){if(battle.turn)return;battle.turn=true;const hero=STARS.find(s=>s.id===state.captain),names={dribble:'Regate',shot:'Disparo',press:'Presión'},base={dribble:18,shot:29,press:13}[type];let hit=base+Math.floor(Math.random()*12);if(type==='shot'&&Math.random()<.2){battleText(`¡El disparo de ${hero.name} se marcha fuera!`);hit=0}else{if(type==='press')battle.shield=7;const crit=Math.random()<.12;if(crit)hit=Math.round(hit*1.5);battleText(`${hero.name} usa ${names[type]}. ${crit?'¡JUGADA PERFECTA! ':''}-${hit} energía.`)}battle.rivalHp-=hit;$('#rival-sprite').animate([{transform:'translateX(0)'},{transform:'translateX(-10px)',filter:'brightness(3)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:330});updateBattle();setTimeout(()=>{if(battle.rivalHp<=0){battle.rivalHp=1;battleText(`${battle.rival.name} está agotado. ¡Ahora es más fácil ficharlo!`);battle.turn=false;updateBattle()}else rivalTurn()},900)}
function rivalTurn(){const r=battle.rival,move=r.moves[Math.floor(Math.random()*r.moves.length)];let damage=9+Math.floor(Math.random()*14);damage=Math.max(3,damage-(battle.shield||0));battle.shield=0;state.hp=Math.max(0,state.hp-damage);save();battleText(`${r.name} usa ${move}. ¡Pierdes ${damage} de energía!`);$('#hero-sprite').animate([{transform:'translateX(0)'},{transform:'translateX(10px)',filter:'brightness(3)'},{transform:'translateX(-8px)'},{transform:'translateX(0)'}],{duration:330});if(state.hp<=0)setTimeout(()=>endBattle(false,true),1200);else{battle.turn=false;updateBattle()}}
function contract(){if(battle.turn||state.balls<1){if(state.balls<1)battleText('No te quedan balones contrato. Busca cofres o visita la tienda.');return}state.balls--;save();battle.turn=true;updateBattle();battleText('¡Lanzas un balón contrato!');const chance=.14+(100-battle.rivalHp)*.0085+(state.owned.includes(battle.rival.id)?.18:0);$('#rival-sprite').animate([{transform:'scale(1)'},{transform:'scale(.1) rotate(360deg)'},{transform:'scale(.1)'},{transform:'scale(1)'}],{duration:1000});setTimeout(()=>{if(Math.random()<chance){if(!state.owned.includes(battle.rival.id))state.owned.push(battle.rival.id);state.wins++;state.coins=(state.coins||0)+30;state.level=Math.min(99,state.level+(state.wins%3===0?1:0));save();battleText(`¡Fichaje conseguido! ${battle.rival.name} se une a tu equipo. +30 monedas.`);setTimeout(()=>endBattle(true),1600)}else{battleText(`¡${battle.rival.name} rechaza el contrato!`);setTimeout(rivalTurn,900)}},1200)}
function endBattle(caught=false,defeat=false){if(defeat){state.x=6;state.y=7;state.hp=100;save();showView('world-view');message('Tu capitán se agotó. Has vuelto al centro médico.')}else{showView('world-view');message(caught?'¡Nuevo futbolista en tu vestuario!':'Has regresado al mapa.')}battle=null;drawWorld()}
function renderTeam(){const list=state.owned.map(id=>STARS.find(s=>s.id===id)).filter(Boolean);$('#team-list').innerHTML=`<div class="team-summary"><b>${list.length}/${STARS.length} jugadores</b><span>🪙 ${state.coins||0} · 🏆 ${state.wins}</span></div>`+list.map(p=>`<article class="player-row"><div class="portrait" style="background:${p.color}">${p.short}</div><div><h3>${p.name}</h3><p>${p.pos} · GRL ${p.rating}</p>${state.captain===p.id?'<span class="captain">★ CAPITÁN</span>':''}</div><button data-id="${p.id}">${state.captain===p.id?'✓':'Elegir'}</button></article>`).join('');$$('.player-row button').forEach(b=>b.onclick=()=>{state.captain=b.dataset.id;state.hp=100;save();renderTeam()})}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.remove('active'));if(id==='world-view')$('#nav-world').classList.add('active');if(id==='team-view'){$('#nav-team').classList.add('active');renderTeam()}if(id==='help-view')$('#nav-help').classList.add('active')}
function startHold(dir){held=dir;const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir];move(...d);clearInterval(moveTimer);moveTimer=setInterval(()=>move(...d),145)}function stopHold(){held=null;clearInterval(moveTimer)}
$$('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();startHold(b.dataset.dir)};b.onpointerup=stopHold;b.onpointerleave=stopHold;b.onpointercancel=stopHold});document.addEventListener('keydown',e=>{const key={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'}[e.key];if(key&&!held){e.preventDefault();startHold(key)}if(e.key===' '){e.preventDefault();action()}});document.addEventListener('keyup',e=>{if(['ArrowUp','w','ArrowDown','s','ArrowLeft','a','ArrowRight','d'].includes(e.key))stopHold()});$('#action-btn').onclick=action;$('#dialog-next').onclick=()=>$('#dialog').classList.remove('show');$('#nav-world').onclick=()=>showView('world-view');$('#nav-team').onclick=()=>showView('team-view');$('#nav-help').onclick=()=>showView('help-view');$$('.close-panel').forEach(b=>b.onclick=()=>showView('world-view'));$$('[data-move]').forEach(b=>b.onclick=()=>attack(b.dataset.move));$('#contract-btn').onclick=contract;$('#run-btn').onclick=()=>endBattle();updateHud();$('#zone-name').textContent=zone();function loop(t){drawWorld(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);dialog('FutMon World se ha expandido: cuatro regiones, un mapa enorme, cofres, tienda y nuevas estrellas te esperan.');
